<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#What-is-Numpy?" data-toc-modified-id="What-is-Numpy?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>What is Numpy?</a></span></li><li><span><a href="#Work-with-numeric-data" data-toc-modified-id="Work-with-numeric-data-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Work with numeric data</a></span></li><li><span><a href="#Go-from-Python-lists-to-Numpy-arrays" data-toc-modified-id="Go-from-Python-lists-to-Numpy-arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Go from Python lists to Numpy arrays</a></span></li><li><span><a href="#Operating-with-Numpy-Arrays" data-toc-modified-id="Operating-with-Numpy-Arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Operating with Numpy Arrays</a></span></li><li><span><a href="#Advantages-of-using-Numpy-arrays" data-toc-modified-id="Advantages-of-using-Numpy-arrays-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Advantages of using Numpy arrays</a></span></li><li><span><a href="#Create-Arrays" data-toc-modified-id="Create-Arrays-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Create Arrays</a></span><ul class="toc-item"><li><span><a href="#random-numbers" data-toc-modified-id="random-numbers-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>random numbers</a></span></li><li><span><a href="#Range" data-toc-modified-id="Range-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Range</a></span></li><li><span><a href="#Linespace" data-toc-modified-id="Linespace-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Linespace</a></span></li><li><span><a href="#around" data-toc-modified-id="around-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>around</a></span></li><li><span><a href="#Arrays-from-data" data-toc-modified-id="Arrays-from-data-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Arrays from data</a></span></li></ul></li><li><span><a href="#Return-a-numpy-array-to-list" data-toc-modified-id="Return-a-numpy-array-to-list-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Return a numpy array to list</a></span><ul class="toc-item"><li><span><a href="#Array-of-ZEROs" data-toc-modified-id="Array-of-ZEROs-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Array of ZEROs</a></span></li><li><span><a href="#Array-of-ONES" data-toc-modified-id="Array-of-ONES-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Array of ONES</a></span></li><li><span><a href="#DIAGONAL-Array" data-toc-modified-id="DIAGONAL-Array-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>DIAGONAL Array</a></span></li></ul></li><li><span><a href="#Dtypes" data-toc-modified-id="Dtypes-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Dtypes</a></span></li><li><span><a href="#Explore-arrays-and-their-properties" data-toc-modified-id="Explore-arrays-and-their-properties-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Explore arrays and their properties</a></span></li><li><span><a href="#Manipulate-arrays" data-toc-modified-id="Manipulate-arrays-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Manipulate arrays</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Transpose" data-toc-modified-id="Transpose-10.0.1"><span class="toc-item-num">10.0.1&nbsp;&nbsp;</span><a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html" rel="nofollow" target="_blank">Transpose</a></a></span></li></ul></li><li><span><a href="#Cannot-transpose-a-list" data-toc-modified-id="Cannot-transpose-a-list-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Cannot transpose a list</a></span></li></ul></li><li><span><a href="#Updating-the-value-of-a-ndim-array" data-toc-modified-id="Updating-the-value-of-a-ndim-array-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Updating the value of a ndim array</a></span></li><li><span><a href="#Array-comparison" data-toc-modified-id="Array-comparison-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Array comparison</a></span></li><li><span><a href="#Array-indexing-and-slicing" data-toc-modified-id="Array-indexing-and-slicing-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Array indexing and slicing</a></span><ul class="toc-item"><li><span><a href="#Mix-of-indexes-and-ranges" data-toc-modified-id="Mix-of-indexes-and-ranges-13.1"><span class="toc-item-num">13.1&nbsp;&nbsp;</span>Mix of indexes and ranges</a></span></li></ul></li><li><span><a href="#Methods-of-np.arrays" data-toc-modified-id="Methods-of-np.arrays-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Methods of np.arrays</a></span><ul class="toc-item"><li><span><a href="#Numpy-methods" data-toc-modified-id="Numpy-methods-14.1"><span class="toc-item-num">14.1&nbsp;&nbsp;</span>Numpy methods</a></span></li></ul></li><li><span><a href="#Fun-things-that-Numpy-allows-us-to-do" data-toc-modified-id="Fun-things-that-Numpy-allows-us-to-do-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Fun things that Numpy allows us to do</a></span></li><li><span><a href="#Some-methods:" data-toc-modified-id="Some-methods:-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>Some methods:</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>Summary</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>Further materials</a></span></li></ul></div>

## ¿Qué es Numpy?

In [1]:
import numpy as np

NumPy es una biblioteca para el lenguaje de programación Python que brinda soporte para crear matrices y vectores multidimensionales de gran tamaño, junto con una gran colección de funciones matemáticas de alto nivel para operar sobre ellos. El precursor de NumPy, Numeric, fue creado originalmente por Jim Hugunin con contribuciones de varios otros desarrolladores. En 2005, Travis Oliphant creó NumPy incorporando características de la competencia Numarray en Numeric, con amplias modificaciones. NumPy es un software de código abierto y cuenta con muchos colaboradores.

El núcleo del paquete NumPy es el objeto ndarray. Este encapsula matrices n-dimensionales de tipos de datos homogéneos, y muchas operaciones se realizan en código compilado para el rendimiento. Existen varias diferencias importantes entre las matrices NumPy y las secuencias estándar de Python:

In [2]:
a = np.array({})
a

array({}, dtype=object)

In [7]:
[i for i in dir (list) if "_" not in i]

['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## Trabajar con datos numéricos
"Datos" en el análisis de datos a menudo se refiere a datos numéricos, por ejemplo, precios de acciones, cifras de ventas, mediciones de sensores, resultados deportivos, tablas de bases de datos, etc. La biblioteca Numpy proporciona estructuras de datos especializadas, funciones y otras herramientas para el cálculo numérico en Python. Trabajemos con un ejemplo para ver por qué y cómo usar Numpy para trabajar con datos numéricos.

Supongamos que queremos usar datos climáticos como temperatura, precipitaciones y humedad para determinar si una región es adecuada para el cultivo de manzanas. Un enfoque simple para hacer esto sería formular la relación entre el rendimiento anual de manzanas (toneladas por hectárea) y las condiciones climáticas como la temperatura media (en grados Fahrenheit), las precipitaciones (en milímetros) y la humedad relativa media (en porcentaje) como una ecuación lineal.

`yield_of_apples = w1 *temperature + w2* rainy + w3 * humidity`

Estamos expresando el rendimiento de manzanas como una suma ponderada de temperatura, precipitaciones y humedad. Esta ecuación es una aproximación, ya que la relación real puede no ser lineal y pueden estar involucrados otros factores. Pero un modelo lineal simple como este suele funcionar bien en la práctica.

Con base en un análisis estadístico de datos históricos, podemos obtener valores razonables para los pesos w1, w2 y w3. A continuación, se muestra un ejemplo de valores:

![np](https://nustat.github.io/DataScience_Intro_python/Datasets/numpy_image.png)

In [ ]:
#yield_of_apples = w1 *temperature + w2* rainfall + w3 * humidity

| Region | Temp. (F) | Rainfall (mm) | Humidity (%) |
|--------|-----------|---------------|--------------|
| Kanto  | 73        | 67            | 43           |
| Johto  | 91        | 88            | 64           |
| Hoenn  | 87        | 134           | 58           |
| Sinnoh | 102       | 43            | 37           |
| Unova  | 69        | 96            | 70           |

Ahora podemos sustituir estas variables en la ecuación lineal para predecir el rendimiento de las manzanas.

In [14]:
w1 = 0.5
w2 = 0.1
w3 = 0.9

pesos = [w1, w2, w3]
kanto = [73, 67, 43]

pesos = np.array(pesos)
kanto = np.array(kanto)

cosa = sum(pesos * kanto)
cosa

np.float64(81.9)

`rendimiento_de_manzanas = w1 *temperatura + w2 * lluvia + w3 * humedad`

Para que el cálculo anterior sea un poco más fácil para múltiples regiones, podemos representar los datos climáticos de cada región como un vector, es decir, una lista de números.

Los tres números de cada vector representan los datos de temperatura, precipitación y humedad, respectivamente.
También podemos representar el conjunto de ponderaciones utilizado en la fórmula como un vector.

¿Cómo podemos calcular el cultivo de cada región?

## Pasar de listas de Python a matrices Numpy
El cálculo realizado por crop_yield (multiplicación de dos vectores elemento por elemento y suma de los resultados) también se denomina producto escalar. Para obtener más información sobre el producto escalar, consulte: https://numpy.org/doc/stable/reference/generated/numpy.dot.html

La biblioteca Numpy proporciona una función integrada para calcular el producto escalar de dos vectores. Sin embargo, primero debemos convertir las listas a matrices Numpy.

Instalemos la biblioteca Numpy utilizando el administrador de paquetes pip.

A continuación, vamos a importar el módulo numpy. Es una práctica habitual importar numpy con el alias np. Se trata de una convención, todos los programadores utilizan los mismos nombres al importar bibliotecas. Realmente funciona si pongo cualquier nombre, en el caso de numpy siempre utilizamos np

## Cómo operar con matrices Numpy

El operador * realiza una multiplicación elemento por elemento de dos matrices si tienen el mismo tamaño. El método suma calcula la suma de los números de una matriz.

Ahora podemos calcular el producto escalar de los dos vectores usando la función np.dot.

Ahora podemos usar la función np.array para crear matrices Numpy.

Podemos lograr el mismo resultado con operaciones de bajo nivel compatibles con las matrices Numpy: realizar la multiplicación elemento por elemento y calcular la suma de los números resultantes.

## Ventajas de usar matrices Numpy

Las matrices de Numpy ofrecen las siguientes ventajas sobre las listas de Python para operar con datos numéricos:

- Facilidad de uso: puede escribir expresiones matemáticas pequeñas, concisas e intuitivas como `(kanto * weights).sum()` en lugar de usar bucles y funciones personalizadas como crop().
- Rendimiento: las operaciones y funciones de Numpy se implementan internamente en C++, lo que las hace mucho más rápidas que usar declaraciones y bucles de Python que se interpretan en tiempo de ejecución.
A continuación, se muestra una comparación de productos escalares realizados con bucles de Python frente a matrices de Numpy en dos vectores con un millón de elementos cada uno.

## Crear matrices
### números aleatorios

[Randint aleatorio](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) vs [Aleatorio aleatorio](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html)

![np](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

`1darray: vector`

In [15]:
vector = np.array([1, 2, 3])
vector.shape

(3,)

`2darray: matriz`

In [20]:
matrix = np.array([[1, 2],[3, 4]])
matrix.shape

(2, 2)

`3darray: tensor`

In [ ]:
tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
#Como llegamos al 6?
tensor[1][0][1]

np.int64(6)

![np](https://storage.googleapis.com/lds-media/images/numpy-vector-matrix-3d-matrix.width-1200.jpg)

Numpy también ofrece algunas funciones útiles para crear matrices de formas deseadas con valores fijos o aleatorios.
Consulte la [documentación](https://numpy.org/doc/stable/reference/routines.array-creation.html) oficial o utilice la función de ayuda para obtener más información.

In [26]:
tensor.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
lista = tensor.tolist()
lista

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

### Rango
Rango con inicio, fin y paso (inicio, fin, paso)

### Linespace
La función linspace de NumPy crea secuencias de valores espaciados uniformemente dentro de un intervalo definido.

Básicamente, especifica un punto de inicio y un punto final para un intervalo y, luego, especifica la cantidad total de puntos de interrupción que desea dentro de ese intervalo (incluidos los puntos de inicio y final). La función np.linspace devolverá una secuencia de valores espaciados uniformemente en ese intervalo.

### around
Nos permite redondear los arrays a los decimales que le digamos 🙃

### Matrices a partir de datos

## Devuelve una matriz numpy a la lista

Cuando tengo un vector puedo usar .tolist o list(putyourarrayhere)

También si hay más dimensiones:

### Matriz de ceros
np.zeros se utiliza para crear la matriz donde todos los elementos son 0. Su sintaxis es:
`np.zeros(shape, dtype=float)`

Donde:
- La forma es el tamaño de la matriz y puede ser unidimensional, bidimensional o de múltiples dimensiones.
- El dtype es float64 de manera predeterminada, pero se puede configurar en cualquier tipo de datos en NumPy.

### Matriz de UNOS
De manera similar a los ceros, también podríamos crear una matriz llena de unos. La sintaxis y los parámetros de np.ones() son idénticos a los de np.zeros().

### Matriz DIAGONAL
Devuelve una matriz bidimensional con unos en la diagonal y ceros en el resto. La sintaxis es:
`np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')`
Donde:
- **N**: INT Especifica el número de líneas en la matriz generada.
- **M**: INT (opcional) El valor predeterminado es None. Especifica el número de columnas en la matriz que se generará. Cuando es None, es igual a N.
- **k**: INT (opcional) El valor predeterminado es 0. 0 es la posición principal de la diagonal. Si k es positivo, crea la diagonal superior con el desplazamiento de k; si k es negativo, crea la diagonal inferior con el desplazamiento de k.
- **dtype**: tipo de datos (opcional) El valor predeterminado es float. Especifica el tipo de datos del elemento de la matriz creada.

## D types

## Explorar matrices y sus propiedades

## Manipular matrices

#### [Transponer](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

`arr10.transpose(2, 1, 0) `

1. Reference of the shape of your array
2. Look at the array you want to match it with
3. Choose the position of that axis depending on the reference array

`Mi valor objetivo (forma de arr10) ¿qué índice tiene en la matriz original (arr20) para que pueda transponerlo (new_array)?`

### No se puede transponer una lista

## Actualización del valor de una matriz ndim

In [30]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

`sobrescribiendo`

In [31]:
a[1][2] = 60
a

array([[ 1,  2,  3],
       [ 4,  5, 60]])

In [ ]:
# a[condicion] = asignacion
a[a == 60] = 656565
a

array([[     1,      2,      3],
       [     4,      5, 656565]])

`usando su índice`

In [36]:
a[1][2]= 6
a

array([[1, 2, 3],
       [4, 5, 6]])

`otra sintaxis`

## Comparación de matrices

Las matrices Numpy también admiten operaciones de comparación como ==, !=, >, etc. El resultado es una matriz de valores booleanos.

La comparación de matrices se utiliza a menudo para contar la cantidad de elementos iguales en dos matrices mediante el método de suma. Recuerde que True se evalúa como 1 y False como 0 cuando se utilizan valores booleanos en operaciones aritméticas.

## Indexación y segmentación de matrices
Numpy extiende la notación de indexación de listas de Python usando [] a múltiples dimensiones de una manera intuitiva. Puede proporcionar una lista separada por comas de índices o rangos para seleccionar un elemento específico o una submatriz (también llamada segmentación) de una matriz Numpy.

In [47]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[10,11,12],[13,14,15],[16,17,18]]],
            [[[19,20,21],[22,23,24],[26,27,28]],
             [[29.30,31],[32,33,34],[35,36,37]]])
a

TypeError: Field elements must be 2- or 3-tuples, got '[[19, 20, 21], [22, 23, 24], [26, 27, 28]]'

`lista separada por comas`

`índices como una lista`

Podemos escribir las posiciones directamente en una lista

### Mezcla de índices y rangos

## Métodos de np.arrays

### Métodos Numpy

## Cosas divertidas que Numpy nos permite hacer

¿Cómo los vemos? `dir(object)` muestra todos los métodos posibles que se pueden aplicar al objeto

Pillow y skimage. La biblioteca de imágenes de Python y skimage agregan capacidades de procesamiento de imágenes a su intérprete de Python. 
- [Pillow](https://pillow.readthedocs.io/en/stable/) `im = Image.open("path")` <br> 
- [skimage](https://scikit-image.org/docs/stable/) `photo = io.imread("path")`

¡Podemos procesar imágenes con Numpy!

In [ ]:
# terminal: conda activate our_env
# pip install library
# jupyter: kernel > change kernel > our_env
# refresh kernel
# import library

`pip3 install scikit-image`

In [ ]:
!pip3 install scikit-image


In [50]:
from skimage import io

ModuleNotFoundError: No module named 'skimage'

![Cubo RGB](https://upload.wikimedia.org/wikipedia/commons/d/d6/RGB_color_cube.svg)

"Explorando la imagen numéricamente"

In [ ]:
photo[0][0] 

# RED: photo[0][0][0] is 227
# GREEN: photo[0][0][1] is 208
# BLUE: photo[0][0][2] is 201

In [ ]:
pic = io.imshow(photo)
pic

In [ ]:
def picture_info(pic):
    
    print(f"Shape of the picture is: {pic.shape}")

    print(f"1. First dimension: {pic.shape[0]} pixels on Y axis\n\n Example: {pic[0]}\n") 
    print(f"2. Second dimension: {pic.shape[1]} pixels on X axis\n\nExample: {pic[0]}\n") 

    print("--------------------------\n")
    print(f"2. Third dimension (RGB) is: {pic[0][0]}\n") 
    print("--------------------------\n")
    print(f"- Red: {pic[0][0][0]}")
    print(f"- Green: {pic[0][0][1]}") 
    print(f"- Blue: {pic[0][0][2]}")
    
picture_info(photo)

In [ ]:
picture_info(photo)

`invertir una imagen`

In [ ]:
reversed_pic = io.imshow(photo[::-1])
reversed_pic

`recortar una imagen`

In [ ]:
io.imshow(photo)

In [ ]:
cathedral = io.imshow(photo[200:500, 400:800])
cathedral

"cambiando de color"

`brillo: alto`

In [ ]:
brightness_high = np.where(photo > 100, 200, 0) # brightness
io.imshow(brightness_high);

# np.where en pandas se suele usar bastante
# unificar mismas categorías de una variable

In [ ]:
brightness_high = np.where(photo > 100, 255, 0) # brightness
io.imshow(brightness_high);

`brillo: bajo`

In [ ]:
brightness_low = np.where(photo > 70, 50, 30)
io.imshow(brightness_low);

# np. where: donde se cumpla la condición, haz X y si no, haz Y
                                        # X, else Y

`color: rojo`

In [ ]:
filter_reds = np.where(photo > 200, photo, 0) # donde se cumpla que sea mayor que 200, devuélveme el mismo valoe, si no -> 0
io.imshow(filter_reds);

In [ ]:
red_filter = np.where(photo > 100, 30, 100)
io.imshow(red_filter);

In [ ]:
filter_3= np.where(photo > 150, 255, 100) # all red, all blue and all green
io.imshow(filter_3);

`color: azules`

In [ ]:
filter_blues = np.where(photo < 200, photo, 0)
io.imshow(filter_blues);

In [ ]:
blue_filter = np.where(photo > 100, 200, photo)
io.imshow(blue_filter);

In [ ]:
filter_ = np.where(photo[:, :, :] > 100, 0, 255)
io.imshow(filter_);

`color: `

In [ ]:
filter_ = np.where(photo[:, :, 2] > 100, 0, 255)
io.imshow(filter_);

In [ ]:
filter_random = np.where(photo[200:500, 400:800, 0] > 150, 90, 50)
io.imshow(filter_random);

In [ ]:
filter_10 = np.where(photo > 207, 0, 255) 
filter_10[0][0]

# array([0, 0, 255], dtype=uint8)

In [ ]:
photo[0][0]

In [ ]:
photo[0][2]

In [ ]:
get_info(photo)

![Cubo RGB](https://www.aseprite.org/docs/color-profile/rgb-cube.png)

## Algunos métodos:

- [Multiplicar](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html)
- [Reformar](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)
- [Transponer](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

## Resumen
Ahora te toca a ti. ¿Qué hemos aprendido hoy?

## Materiales adicionales
- [Hoja de referencia de NumPy](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
- [Domina Numpy](https://medium.com/analytics-vidhya/master-numpy-in-45-minutes-74b2460ecb00)
- [Trucos de Numpy](https://github.com/patidarparas13/Numpy-Tricks/blob/master/Numpy%2BTricks(Zero%2Bto%2BHero).ipynb)
- [101 ejercicios de Numpy](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)